version: '3.8'

services:
  combat-sheet:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: disparter/combat-sheet:v1.0
    env_file:
      - .env
    environment:
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=${MONGO_AUTO_INDEX_CREATION}
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_DB_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_DB_PASSWORD}
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_DB}
      - SPRING_DATA_MONGODB_URI=${MONGO_DB_URL}
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo:5.0
    networks:
      - mongo-compose-network
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - $MONGO_DATA_HOST_PATH:/var/mongo/data
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    command: [ "--bind_ip", "0.0.0.0" ]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
        - ME_CONFIG_MONGODB_URL=${MONGO_DB_URL}
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
    volumes:
      - /var/mongo/data:/data/db


networks:
  mongo-compose-network:
    driver: bridge
