version: '3.8'

services:
  combat-sheet:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: disparter/combat-sheet:v1.0
    env_file:
      - .env
    environment:
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_URI=$MONGO_DB_URI
    depends_on:
      - mongo

  mongo:
    build:
      network: bridge
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
      - PUID=1000
      - PGID=1000
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    command: [ "--bind_ip", "0.0.0.0" ]

  mongo-express:
    build:
      network: bridge
    image: mongo-express
    container_name: mongo-express
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_DB_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_DB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_DB_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_DB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=$MONGO_DB
      - ME_CONFIG_MONGODB_URL=mongo://mongo:mongo@combat-sheet:27017
    depends_on:
      - mongo
